Component refactoring to use the new token structure
selsa-inube/inubekit-label pull request #4
Opened 2024-02-21 21:25 UTC by JanuarAsprilla

On this card the component is refactored to use the new token structure

2024-02-21 21:43 UTC, cmarin001 approved these changes
meet the requirements, however make sure that label minor is on it

2024-02-22 17:57 UTC, wfercanas requested changes

2024-02-22 17:57 UTC, wfercanas commented on src/Label/ typography.ts
No es necesario agregar todos los tipos de texto. Con agregar `label` es suficiente.

2024-02-22 17:57 UTC, wfercanas commented on src/Label/styles.js
> +import { typography } from "./ typography";
Es espacio entre ./ y typography genera error

2024-02-22 17:57 UTC, wfercanas commented on src/Label/styles.js
> +import { typography } from "./ typography";
Esta variable se está importando pero no se está usando

2024-02-22 17:57 UTC, wfercanas commented on src/Label/styles.js
>    font-family: ${({ theme }) => {
Debajo de esta propiedad, se siguen definiento propiedades como font-size, font-weight y demás usando theme.typography o inube.typography. Esos tokens ya no existen.

Para estas propiedades es que creó el archivo typography.ts, para no tener que usar estos tokens

2024-02-23 17:26 UTC, JanuarAsprilla commented on src/Label/styles.js
> +import { typography } from "./ typography";
corregido

2024-02-23 17:26 UTC, JanuarAsprilla commented on src/Label/styles.js
>    font-family: ${({ theme }) => {
corregido

2024-02-23 17:33 UTC, cmarin001 commented on src/Label/ typography.ts
this issue still happen
![image](https://github.com/selsa-inube/inubekit-label/assets/45011420/de919a44-8f00-4623-a10a-389a7d9ef2a0)

2024-02-23 17:49 UTC, JanuarAsprilla commented on src/Label/ typography.ts
solved

2024-02-23 18:03 UTC, cmarin001 commented on src/Label/ typography.ts
solved

2024-02-26 17:14 UTC, wfercanas approved these changes

2024-02-26 17:14 UTC, merged